name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Check out the commit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ~${{ matrix.version }}

      - name: Install development dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            -r requirements.txt \
            -r doc/requirements.txt \
            -r example/requirements.txt \
            -r test/requirements.txt

      - name: Test install
        run: python3 -m pip install .

      - name: Test with pytest
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: python3 -m pytest --verbose --cov=shell_logger test/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Check documentation coverage
        run: make coverage SPHINXOPTS="-W --keep-going"
        working-directory: ./doc

      - name: Archive documentation coverage results
        uses: actions/upload-artifact@v4
        with:
          name: docs-coverage-report
          path: doc/build/coverage/python.txt

      - name: Test uninstall
        run: python3 -m pip uninstall -y shell-logger

  commits:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Conventional Commits
        uses: taskmedia/action-conventional-commits@v1.1.14
        with:
          types: >
            build|chore|ci|docs|feat|fix|minor|patch|perf|style|refactor|test
